-- liquibase formatted sql

-- changeset D1:1660647858188-1
CREATE TABLE giftcards (TransactionId INT NOT NULL, CardNumber VARCHAR(45) NOT NULL, CardPIN VARCHAR(45) NOT NULL, Amount INT NOT NULL, ApprovalCode VARCHAR(45) NOT NULL, AddonCardNumber VARCHAR(45) NOT NULL, MerchantName VARCHAR(45) NOT NULL, DiscountAmount INT NOT NULL, PaymentType VARCHAR(45) NOT NULL, ResponseMessage VARCHAR(45) NOT NULL, MerchantOutletAddress1 VARCHAR(45) NOT NULL, MerchantOutletAddress2 VARCHAR(45) NOT NULL, MerchantOutletCity VARCHAR(45) NOT NULL, MerchantOutletState VARCHAR(45) NOT NULL, MerchantOutletCountry VARCHAR(45) NOT NULL, MerchantOutletPinCode VARCHAR(45) NOT NULL, ReceiptFooterLine1 VARCHAR(45) NOT NULL, ReceiptFooterLine2 VARCHAR(45) NOT NULL, ReceiptFooterLine3 VARCHAR(45) NOT NULL, ReceiptFooterLine4 VARCHAR(45) NOT NULL, CardType VARCHAR(45) NOT NULL, TransactionResult VARCHAR(45) NOT NULL, CONSTRAINT PK_GIFTCARDS PRIMARY KEY (TransactionId), UNIQUE (TransactionId));
INSERT INTO giftcards (TransactionId,CardNumber,CardPIN,Amount,ApprovalCode,AddonCardNumber,MerchantName,DiscountAmount,PaymentType,ResponseMessage,MerchantOutletAddress1,MerchantOutletAddress2,MerchantOutletCity,MerchantOutletState,MerchantOutletCountry,MerchantOutletPinCode,ReceiptFooterLine1,ReceiptFooterLine2,ReceiptFooterLine3,ReceiptFooterLine4,CardType,TransactionResult) VALUES (1,'606721323290','1869',2000,'approved10','606721322234','Pavan Ananthoju',20,'Card','Success','Telecomnagar','Gachibowli','Hyderabad','Telangana','India','500032','Thank you','You','are','welcome','Visa','Successs');
INSERT INTO giftcards (TransactionId,CardNumber,CardPIN,Amount,ApprovalCode,AddonCardNumber,MerchantName,DiscountAmount,PaymentType,ResponseMessage,MerchantOutletAddress1,MerchantOutletAddress2,MerchantOutletCity,MerchantOutletState,MerchantOutletCountry,MerchantOutletPinCode,ReceiptFooterLine1,ReceiptFooterLine2,ReceiptFooterLine3,ReceiptFooterLine4,CardType,TransactionResult) VALUES (2,'606721323290','1869',2000,'approved10','606721322234','Pavan Ananthoju',20,'Card','Success','Telecomnagar','Gachibowli','Hyderabad','Telangana','India','500032','Thank you','You','are','welcome','Visa','Successs');

-- changeset D1:1660647858188-2
CREATE TABLE reservations (restaurantId INT NOT NULL, reservationTime VARCHAR(45) NOT NULL, reservationDate VARCHAR(45) NOT NULL, noOfPeople INT NOT NULL, customerId INT NOT NULL, lastName VARCHAR(45) NOT NULL, firstName VARCHAR(45) NOT NULL, reservationNotes VARCHAR(45) NOT NULL, mobile VARCHAR(45) NOT NULL, landline VARCHAR(45) NOT NULL, email VARCHAR(45) NOT NULL, interfaceId INT NOT NULL, occasion VARCHAR(45) NOT NULL, eatNowFlag INT NOT NULL, sessionName VARCHAR(45) NOT NULL, sessionId INT NOT NULL, sourceApp VARCHAR(45) NOT NULL, packageName VARCHAR(45) NOT NULL, tableNo VARCHAR(45) NOT NULL, tableStatus VARCHAR(45) NOT NULL, waitListedFlag INT NOT NULL, strLocTitle VARCHAR(45) NOT NULL, CONSTRAINT PK_RESERVATIONS PRIMARY KEY (restaurantId));
INSERT INTO reservations (restaurantId,reservationTime,reservationDate,noOfPeople,customerId,lastName,firstName,reservationNotes,mobile,landline,email,interfaceId,occasion,eatNowFlag,sessionName,sessionId,sourceApp,packageName,tableNo,tableStatus,waitListedFlag,strLocTitle) VALUES (1,'8pam','10/05/2022',4,1869,'Pavan','Ananthoju','Blue Table','9703562234','200500','pavan92000@gmail.com',100,'birthday',1,'dinner',1020,'Zomato','Family','Five','reserved',98,'no');
INSERT INTO reservations (restaurantId,reservationTime,reservationDate,noOfPeople,customerId,lastName,firstName,reservationNotes,mobile,landline,email,interfaceId,occasion,eatNowFlag,sessionName,sessionId,sourceApp,packageName,tableNo,tableStatus,waitListedFlag,strLocTitle) VALUES (2,'8pam','10/05/2022',4,1869,'Pavan Kumar Up','Ananthoju','Blue Table','9703562234','200500','pavan92000@gmail.com',100,'birthday',1,'dinner',1020,'Zomato','Family','Five','reserved',98,'no');
