-- liquibase formatted sql

-- changeset D1:1661167035143-1
CREATE TABLE area (areaid INT NOT NULL, Address_line VARCHAR(45) NOT NULL, Colony VARCHAR(45) NOT NULL, place VARCHAR(45) NOT NULL, pincode VARCHAR(45) NOT NULL, CONSTRAINT PK_AREA PRIMARY KEY (areaid), UNIQUE (areaid));

-- changeset D1:1661167035143-2
CREATE TABLE trainees (id INT NOT NULL, name VARCHAR(450) NOT NULL, age VARCHAR(450) NOT NULL, area INT NOT NULL, CONSTRAINT PK_TRAINEES PRIMARY KEY (id), UNIQUE (id));

